# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
server: &server
  adapter: postgresql
  encoding: unicode
  reconnect: false
  pool: 5
  host: 127.0.0.1
  port: 5432
  username: postgres
  password: postgres

development:
  adapter: sqlite3
  encoding: unicode
  reconnect: false
  pool: 5
  database: embedruby

test: &test
  <<: *server
  database: embedruby_test

production:
  <<: *server
  database: embedruby


cucumber:
  <<: *test
